### ISSUE TITLE
Bot 'likes'

### ISSUE THREAD

**Issue by RONTheCookie** [jellz/discordboats.club#13]
Similar to upvotes, but not. 

Users can "like" bots they enjoy using, and they will behave like upvotes in the sense of being able to be rewarded inside the bot. However, they will be permanent & won't reset every 24 hours or every month or anything like that. A User's Liked Bots will show on their profile, too.

**Comment by jellz** [comment]
In regards to this image here I accidentally referenced the wrong commit aaa
![image](https://user-images.githubusercontent.com/24366082/39418488-0d691b08-4c9e-11e8-8f27-fa422f9e6a64.png)

**Comment by RONTheCookie** [comment]
backend is done for this
