### ISSUE TITLE
No images on mobile

### ISSUE THREAD

**Issue by sdfsdfsdf1234** [jellz/discordboats.club#37]
On mobile, no profile pictures show up

**Comment by RONTheCookie** [comment]
Which browser are you using?

**Comment by sdfsdfsdf1234** [comment]
I'm on the latest version of mobile chrome on an iPhone 6s iOS 11.3

**Comment by sdfsdfsdf1234** [comment]
https://cdn.discordapp.com/attachments/424821989115691009/437302007104274452/image.png
https://cdn.discordapp.com/attachments/424821989115691009/437302006584049664/image.png

**Comment by RONTheCookie** [comment]
Changed some stuff in https://github.com/jellz/discordboats.club/commit/8419c59bfd4e85e59700333db33f739e3e715a8e, could you try again now?

**Comment by sdfsdfsdf1234** [comment]
It works now

**Comment by RONTheCookie** [comment]
Good! :smile:
