### ISSUE TITLE
When inputting special characters the description breaks

### ISSUE THREAD

**Issue by RileyDatLord** [jellz/discordboats.club#40]
### Expected behaviour?
 Puts in the special character (ex: >)
### Actual behaviour?
 Puts out the code for the character (ex: > would be turned to "\&gt;")
### Steps to reproduce?
 Put in any special character
### Any additional information?
 Like all my bots use special characters like `>`

**Comment by RONTheCookie** [comment]
fixed in https://github.com/jellz/discordboats.club/commit/3c5253336f991defc59f6380358bfe88ce88f79a
