### ISSUE TITLE
The Number for the heart is bugged

### ISSUE THREAD

**Issue by telkenes** [jellz/discordboats.club#56]
# Issue Template
**Only use this template if you are reporting a bug! Delete this if you are suggesting a feature.**

### Expected behaviour?
the number centered

### Actual behaviour?
https://gyazo.com/8f1e96f46e9f5f02be83d15893f5985a look

### Steps to reproduce?
fix where the number is

### Any additional information?
is it only for me?
im using chrome(mac os)

**Comment by RileyDatLord** [comment]
This is not just for you, I'm using Chrome (Win 10) and it isn't.
