### ISSUE TITLE
Deleteing Bot doesnt log in the guild

### ISSUE THREAD

**Issue by telkenes** [jellz/discordboats.club#57]
# Issue Template
**Only use this template if you are reporting a bug! Delete this if you are suggesting a feature.**

### Expected behaviour?
Deleteing a Bot logs "user deleted x bot by y and z" in the guild

### Actual behaviour?
Doesnt Do Anything but removes the bot

### Steps to reproduce?
make it log

### Any additional information?
nothing rlly

**Comment by RONTheCookie** [comment]
we dont show deletion logs for privacy, issue closed.
