### ISSUE TITLE
Dark theme text inputs have a hard to read text color

### ISSUE THREAD

**Issue by sdfsdfsdf1234** [jellz/discordboats.club#58]
### Expected behaviour?
The color should be a light color, making it more readable.

### Actual behaviour?
The color is dark and hard to read

### Steps to reproduce?
-Make sure you're in dark theme
-Go to the home page
-Type something into the search field

### Any additional information?
This also happens on other input fields besides the search one, like the add/edit bot page
http://sdf-images.000webhostapp.com/i/ece873.png

**Comment by RONTheCookie** [comment]
your webserver isnt working

**Comment by RONTheCookie** [comment]
fixed :ok_hand: (:
