### ISSUE TITLE
Github Link doesnt work.

### ISSUE THREAD

**Issue by razod** [jellz/discordboats.club#61]
# Issue Template
**Only use this template if you are reporting a bug! Delete this if you are suggesting a feature.**

### Expected behaviour?
I put my github link in the github text area, and my short description in its area and the long description on its textarea. So basically the github link should be in its button and the descriptions should stay in their own text area.
### Actual behaviour?
It makes the github link go into the short description and the short description into the full description. And then the full description is gone.
### Steps to reproduce?
Put in a github link, a short description, and a full description into ur bot and it will happen.

**Comment by telkenes** [comment]
seems to be working might be only on ur side ¯\_(ツ)_/¯

**Comment by jellz** [comment]
It has since been fixed.
