### ISSUE TITLE
HTML in description & removal of char limit

### ISSUE THREAD

**Issue by Cairo2k18** [jellz/discordboats.club#67]
You should allow HTML to be used in bot's long description and remove the character limit. Doing this would make bot's pages much more custom and unique.

**Comment by ThatTonybo** [comment]
HTML is dangerous and harder to implement, plus it'd need constant moderation for malicious scripts, dangerous code, etc. Adds more work to moderators plus it gives the risk of ruining the website.

**Comment by jellz** [comment]
Sanitizing the HTML is easier than you think.

**Comment by ThatTonybo** [comment]
It still requires some effort, and I don't see why Markdown isn't enough, it work's fine.

**Comment by jellz** [comment]
Of course it requires effort. That isn’t a problem. I agree with you though, Markdown is enough.

**Comment by jellz** [comment]
v2 will have HTML support and a 6x longer character limit.
