### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by jellz** [jellz/discordboats.club#8]
Should include - 

- [x] API key per bot https://github.com/jellz/discordboats.club/commit/6be3d59a3d56bd43221c5fe8caa061cee1677957
- [x] Endpoint to regenerate API key for bot
- [x] Endpoint to POST new guild count for bot
- [x] Endpoint to GET info of bot https://github.com/jellz/discordboats.club/commit/6be3d59a3d56bd43221c5fe8caa061cee1677957
- [ ] Endpoint to GET recent bots, featured bots, etc.
- [x] Documentation

**Comment by RONTheCookie** [comment]
done - the thing that is unchecked is not applicable atm
